version: '3.8'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-client      
    ports:
      - "5433:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fiap-lanchonete-network

  fiap-lanches-client-api:
    image: dalexandrias/fiap-lanches-client-app:latest
    ports:
      - "8086:8086"
    volumes:
      - fiap-lancher:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db
    networks:
      - fiap-lanchonete-network

networks:
  fiap-lanchonete-network:
    driver: bridge

volumes:
  postgres-db:
    driver: local
  fiap-lancher:
    driver: local
