spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/fiap-lanches-client}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin123}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
management:
  endpoints:
    web:
      exposure:
        include: health
server:
  port: 8085


logging:
  level:
    root: error
    org.springframework: error

app:
  db:
    init:
      enabled: true
